language: node_js
env:
  - NODE_ENV=production

node_js:
  - "10.15.3"

branches:
  only:
    - master
sudo: required

before_install:
  - npm install -g yarn # yarn을 글로벌로 설치
  # 테스트

services:
  - docker

script:
  - cd client && yarn install --prod && CI="false" yarn build && cd -
  - cd server && yarn && cd -

cache:
  yarn: true

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker build -t $DOCKER_USERNAME/onad_landing ./client
  - docker build -t $DOCKER_USERNAME/onad_landing_api ./server
  - docker tag $DOCKER_USERNAME/onad_landing $DOCKER_USERNAME/onad_landing:0.$TRAVIS_JOB_NUMBER
  - docker tag $DOCKER_USERNAME/onad_landing_api $DOCKER_USERNAME/onad_landing_api:0.$TRAVIS_JOB_NUMBER
  - docker push $DOCKER_USERNAME/onad_landing
  - docker push $DOCKER_USERNAME/onad_landing_api

# slack notification for one channel
notifications:
  email: false
  slack: onadworkspace:GAoJDTE0OUEwadREAoZizqFz
